name: Dev Builds
on:
  push:
    branches: [ '**' ]
    paths-ignore: ['*.md']
  pull_request:

env:
  IS_THIS_RELEASE: false

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'SKIP') }}
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_USERNAME: ${{ secrets.GH_USERNAME }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6

      - name: Setup jdk
        uses: actions/setup-java@v5
        with:
          distribution: 'liberica'
          java-version: '25'

      - name: Cache Gradle dependencies
        id: gradle-cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ./.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-common
            ${{ runner.os }}-gradle-

      - name: Make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: Get latest short hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Download dependencies
        if: |
          steps.gradle-cache.outputs.cache-hit != 'true' ||
          contains(github.event.head_commit.message, 'DEPS')
        run: ./gradlew dependencies --stacktrace

      - name: Build
        run: ./gradlew :fabricWrapper:build

      - name: Capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: litematica-printer-multi-${{ env.COMMIT_HASH }}
          path: fabricWrapper/build/libs/*.jar

      - name: Capture build artifacts single version
        uses: actions/upload-artifact@v7
        with:
          name: litematica-printer-single-${{ env.COMMIT_HASH }}
          path: fabricWrapper/build/tmp/submods/META-INF/jars/*.jar

  summary:
    runs-on: ubuntu-latest
    if: ${{ !contains(github.event.head_commit.message, 'SKIP') }}
    needs:
      - build

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-python@v6
        with:
          python-version: 3.12

      - name: Get latest short hash
        run: echo "COMMIT_HASH=$(git rev-parse --short HEAD)" >> $GITHUB_ENV

      - name: Download build artifacts
        uses: actions/download-artifact@v8
        with:
          name: litematica-printer-single-${{ env.COMMIT_HASH }}
          path: build-artifacts

      - name: Make build summary
        run: |
          pip install jproperties
          python .github/workflows/scripts/summary.py
        env:
          TARGET_SUBPROJECT: ${{ inputs.target_subproject }}